### ISSUE TITLE
]

### ISSUE THREAD

**Issue by Git-Banl** [Linkontoask/v-easy#2]
index.js?bed3:167 ./node_modules/v-easy-message/lib/tooltip/src/directive.js
Module parse failed: Unexpected token (75:16)
You may need an appropriate loader to handle this file type.
| 
|             let data = simple ? {
|                 ...value,
|                 placement: value['placement'] || 'top',
|                 vNode: typeof value['vNode'] === 'function' && value['vNode'](),
 @ ./node_modules/v-easy-message/lib/tooltip/index.js 1:0-40
 @ ./node_modules/v-easy-message/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8000 webpack/hot/dev-server ./src/main.js

**Comment by Linkontoask** [comment]
请移步到 [地址](https://github.com/Linkontoask/v-easy-ui)，在新版仓库中记下issues并还原使用场景。目前项目还属于开发阶段，请不要在生产环境中使用
